# Site
repository: DylanLawless/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info 
name: Dylan Lawless
title: Postdoctoral researcher, Switzerland
email: dylan.lawless@epfl.ch
website: https://lawlessgenomics.com
resumePDF: yes

# darkmode: false

# Social links
twitter_username: meddlaw
github_username:  dylanlawless
# dribbble_username: jekyll
# facebook_username: jekyll
flickr_username: jekyll
instagram_username: lawless.ch
linkedin_username: dylan-lawless-human-genomics
# pinterest_username: jekyll
# youtube_username: globalmtb
googlescholar_username: citations?hl=de&user=RPBxP1wAAAAJ
orcid_username: 0000-0001-8496-3725

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
  
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Postdoc scientist. 
  Human genomics & immunology. 
  Large-scale bioinformatics and wet-lab, molecular genetics, immunology. 
  WGS, exome, SNV, CNV, rare disease, RNAseq, somatic mutation, pipeline dev, statistics.
  Current projects in host-pathogen genomic interactions to viruses, bacterial sepsis, and genetic susceptibility to immune disorders.
  Data types include whole genome sequencing, GWAS, pathogen sequencing, methylation, RNA, 
  an array of other clinical data.
  I specialise in the genetics of the primary immune system and response to infection.
  Working with a wide range of specialists from international teams. Collaborative research projects in human health with a lasting impact based on open, reproducible science.

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

awards_title: Awards

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#  Other skills
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [url link](https://www.youtube.com/)


# Footer
footer_show_references: true

# Build settings
# remote_theme: Dylan-Lawless/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

future: true
